apiVersion: v1
kind: Service
metadata:
  name: onboarding-web
  labels:
    app.kubernetes.io/name: onboarding-web
spec:
  selector:
    app.kubernetes.io/name: onboarding-web
  ports:
    - name: http
      port: 8080
      targetPort: http
