{{- range .Values.servers }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: mcp-servers
---
{{- end }}
