apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus-envoy
  labels:
    app.kubernetes.io/name: prometheus-envoy
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: prometheus-envoy
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
